name: release-tag

on:
  push:
    branches:
      - main

jobs:
  release_on_push:
    name: Make Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          # If the PR has the label release:major, release:minor, or release:patch, this will override bump_version_scheme
          bump_version_scheme: patch
